const ALGOLIA_APPLICATION_ID = 'JDMQGRNX7K';
const ALGOLIA_SEARCH_ONLY_API_KEY = '7f88af4a8740a4559e15f509a39ca83d';
const ALGOLIA_INDEX_NAME = 'speakers';

export {
  ALGOLIA_APPLICATION_ID,
  ALGOLIA_SEARCH_ONLY_API_KEY,
  ALGOLIA_INDEX_NAME,
};
